### ISSUE TITLE
INVALID_PROTOCOL: ah

### ISSUE THREAD

**Issue by evgkrsk** [t-woerner/firewalld#108]
After upgrade firewalld from 0.3.13 to 0.4.1.2:

```
root@thinkpad ~ #LC_ALL=C systemctl status firewalld
* firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-05-01 23:58:53 KRAT; 34min ago
  Process: 18022 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 16490 (firewalld)
   CGroup: /system.slice/firewalld.service
           `-16490 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

May 01 23:58:53 thinkpad.evg-krsk.dyndns.org systemd[1]: Stopped firewalld - dynamic firewall daemon.
May 01 23:58:53 thinkpad.evg-krsk.dyndns.org systemd[1]: Starting firewalld - dynamic firewall daemon...
May 01 23:58:53 thinkpad.evg-krsk.dyndns.org systemd[1]: Started firewalld - dynamic firewall daemon.
May 01 23:58:54 thinkpad.evg-krsk.dyndns.org firewalld[16490]: ERROR: ipset not usable, disabling ipset usage in firewall.
May 01 23:58:54 thinkpad.evg-krsk.dyndns.org firewalld[16490]: ERROR: Failed to load service file '/usr/lib/firewalld/services/ipsec.xml': INVALID_PROTOCOL: ah
```

seems like ah/esp missing somewhere in the code.

**Comment by t-woerner** [comment]
It seems that these protocols are not listed in /etc/protocols on your machine and/or are not resolvable by getprotobyname.

What is the output of
`python -c 'import socket; print(socket.getprotobyname("ah"));'`
and
`python -c 'import socket; print(socket.getprotobyname("esp"));'`

**Comment by evgkrsk** [comment]
You are right:
```
evg@thinkpad ~ $python -c 'import socket; print(socket.getprotobyname("ah"));'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.error: protocol not found
evg@thinkpad ~ $python -c 'import socket; print(socket.getprotobyname("esp"));'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.error: protocol not found
```

**Comment by evgkrsk** [comment]
Editing /etc/protocols leads to error disappearing:
```
root@thinkpad ~ #LC_ALL=C systemctl status firewalld.service
* firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-05-02 20:40:03 KRAT; 1min 47s ago
 Main PID: 2747 (firewalld)
   CGroup: /system.slice/firewalld.service
           `-2747 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

May 02 20:40:03 thinkpad.evg-krsk.dyndns.org systemd[1]: Starting firewalld - dynamic firewall daemon...
May 02 20:40:03 thinkpad.evg-krsk.dyndns.org systemd[1]: Started firewalld - dynamic firewall daemon.
May 02 20:40:03 thinkpad.evg-krsk.dyndns.org firewalld[2747]: ERROR: ipset not usable, disabling ipset usage in firewall.
```

**Comment by t-woerner** [comment]
Is there a distribution that is not shipping this file as part of a minimal installation?

**Comment by evgkrsk** [comment]
Nope, file is present, but protocols definitions are wrong: https://bugzilla.altlinux.org/show_bug.cgi?id=32052

Thanks for quick reply! :-)
