### ISSUE TITLE
wish to install firewalld 0.4.1.2 on CentOs 7

### ISSUE THREAD

**Issue by rroopstr** [t-woerner/firewalld#115]
I notice in ./configure that:
checking for python version... 2.7
checking for python platform... linux2
configure: error: glib-compile-schemas not found.

My current python version is 3.5 which I installed yesterday. How can I get rid of 2,7 ?
I had many firewalld conflicts today with the pythos 3.5 I installed yesterday. Iptables didn't work either. So I uninstalled both of them and downloaded from source firewalld-0.4.1.2.tar.bz2
After README I notice there are many important files for installation: Firewalld.spec  Makefile.am   Makefile.in   fix_python_shebang.sh  py-compile
How should I continue installation? Below is output from my recent failure of previous version of firewalld

sudo systemctl enable firewalld
sudo systemctl start firewalld
sudo firewall-cmd --permanent --add-service=ssh
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAu                                thorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAu                                thorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

[root@mlp config]# sudo firewall-cmd --permanent --add-service=http
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAu                                thorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAu                                thorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

[root@mlp config]# sudo firewall-cmd --permanent --add-service=https
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAu                                thorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAu                                thorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

[root@mlp config]# sudo firewall-cmd --permanent --add-service=smtp
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAu                                thorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAu                                thorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

[root@mlp config]# firewall-cmd --add-service=dns
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py                                                                   ", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service                                                                   .py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handl                                                                   er)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.                                                                   py", line 270, in IsSystemBusNameAuthorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.                                                                   py", line 256, in IsSystemBusNameAuthorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py                                                                   ", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection                                                                   .py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

[root@mlp config]# sudo firewall-cmd --get-services
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAu                                thorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAu                                thorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

[root@mlp config]# sudo firewall-cmd --permanent --list-all
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAu                                thorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAu                                thorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

[root@mlp config]# sudo firewall-cmd --reload
Error: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/slip/dbus/service.py", line 148, in wrapped_method
    reply_handler=reply_handler, error_handler=error_handler)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 270, in IsSystemBusNameAu                                thorizedAsync
    reply_handler, error_handler, challenge, details)
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 256, in IsSystemBusNameAu                                thorizedAsync
    timeout=method_call_no_timeout)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 137, in __call__
    **keywords)
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 584, in call_async
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict

systemctl status firewalld.service
* firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Fri 2016-05-27 17:09:14 BOT; 11s ago
  Process: 2202 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 2202 (code=exited, status=0/SUCCESS)

May 27 17:07:44 mlp systemd[1]: Starting firewalld - dynamic firewall daemon...
May 27 17:07:44 mlp firewalld[2202]: 2016-05-27 17:07:44 ERROR: ebtables not usable, disabling ethernet bridge firewall.
May 27 17:09:14 mlp systemd[1]: firewalld.service start operation timed out. Terminating.
May 27 17:09:14 mlp systemd[1]: Failed to start firewalld - dynamic firewall daemon.
May 27 17:09:14 mlp systemd[1]: Unit firewalld.service entered failed state.
May 27 17:09:14 mlp systemd[1]: firewalld.service failed.

ps -efc
root       915   898 TS   19 16:40 pts/0    00:00:00 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid --debug 10
root      1882   898 TS   19 16:51 pts/0    00:00:00 /usr/bin/python -Es /usr/bin/firewall-cmd --permanent --add-service=ssh

**Comment by rroopstr** [comment]
# whereis python
python: /usr/bin/python 
/usr/bin/python2.7 
/usr/bin/python2.7-config 
/usr/lib/python2.7 
/usr/lib64/python2.7 
/etc/python 
/usr/local/bin/python3.5-config 
/usr/local/bin/python3.5m-config 
/usr/local/bin/python3.5m 
/usr/local/bin/python3.5 
/usr/local/lib/python3.5

**Comment by t-woerner** [comment]
Do you want to use python2 or python3?
In the firewalld repo there is a firewalld.spec file. With this it is simply to generate packages for Fedora and also RHEL >= 7. For RHEL-7 it is still using python2, for Fedora >= 23 python3. TO build a package with it you can simple do the following in the root directory of the firewalld source tree:

```
./autogen.sh
make test-rpm
```

Or you can use

```
rpmbuild -ta firewalld-0.4.2.tar.gz
```

with a release from https://fedorahosted.org/released/firewalld/ or https://github.com/t-woerner/firewalld/releases

**Comment by rroopstr** [comment]
Both python 2 and python 3. I have not yet dared to install anything until
instructions become crystal clear. Because mailman core uses python 3 and
mailman bundler uses python 2 due to installation of Hyperkitty and
Postorius

Rubén Rivero Capriles
http://www.rubenrivero.net (blog global - español)
http://www.rroopstr.com (global blog - English)
http://www.riverocooper.com (art & mining)


2016-06-01 4:12 GMT-04:00 Thomas Woerner <notifications@github.com>:

**Comment by t-woerner** [comment]
There are also 0.4.2 test package available here: http://people.redhat.com/twoerner/firewalld/0.4.2-1.el7/
Please remember that there are additional selinux policy changes required for this version (also to 0.4.1.2). Please have a look at the SELINUX.README in that directory and use the new firewalld-0.4.te file (module firewalld-0.4 version 1.1) from there.

**Comment by Xardas999** [comment]
I've tried to install the latest version of firewalld on CentOS7 server (minimal ISO) without any success.  The package 0.4.XXX missing in all official CentOS repos (+EPEL, REMI) so I really don't know how can I use the latest release of firewalld on CentOS 7. Could you pls provide the instructions how to install?

**Comment by t-woerner** [comment]
Please have a look at RHEl 7.3. It provides the firewalld version 0.4.3.2 with additional upstream patches.

**Comment by Xardas999** [comment]
thank you!
