### ISSUE TITLE
sometime call to reload fails

### ISSUE THREAD

**Issue by kiorky** [t-woerner/firewalld#12]
Im trying already to make a patch for that, basically the problem is here:

https://github.com/t-woerner/firewalld/blob/master/src/firewall/core/fw_direct.py#L93

rule_id is not defined.

```

Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/files/usr/bin/ms_firewalld.py", line 473, in _main
    apply_retry=apply_retry, **kwargs)
  File "/srv/mastersalt/makina-states/files/usr/bin/ms_firewalld.py", line 249, in define_zone
    lazy_reload()
  File "/srv/mastersalt/makina-states/files/usr/bin/ms_firewalld.py", line 166, in lazy_reload
    fw().reload()
  File "<string>", line 2, in reload
  File "/usr/lib/python2.7/dist-packages/slip/dbus/polkit.py", line 103, in _enable_proxy
    return func(*p, **k)
  File "<string>", line 2, in reload
  File "/usr/lib/python2.7/dist-packages/firewall/client.py", line 52, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/firewall/client.py", line 1839, in reload
    self.fw.reload()
  File "/usr/lib/python2.7/dist-packages/slip/dbus/proxies.py", line 50, in __call__
    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.fedoraproject.FirewallD1.Exception: global name 'rule_id' is not defined
```

**Comment by kiorky** [comment]
i have the fix, preparing the PR.
