### ISSUE TITLE
Using subprocess module to run programs leads to huge speedup

### ISSUE THREAD

**Issue by SunilMohanAdapa** [t-woerner/firewalld#132]
When `core/prog.py:runProg()` is replaced with a simpler implementation using Python's subprocess module, there is a significant speed up in startup and shutdown time.

Using os.fork() and 1024 os.close() calls:
```
real    0m22.993s
user    0m18.952s
sys     0m1.124s
```
Using subprocess module:
```
real    0m4.323s
user    0m1.000s
sys     0m0.624s
```

**Comment by t-woerner** [comment]
I do not see this speed up with the new runProg. Do you have lots of direct rules in use? Have you enabled the IndividualCalls setting in firewalld.conf?

**Comment by t-woerner** [comment]
23 seconds is way too long. With the transaction model I am not able to get there easily.

**Comment by SunilMohanAdapa** [comment]
Looks like this kind of bad performance is only reproducible with `--debug 10`.  The attached log shows my list of rules (no direct rules, no change in configuartion except default zone) the time taken for each step : 
[slow_log.txt](https://github.com/t-woerner/firewalld/files/335278/slow_log.txt)

**Comment by t-woerner** [comment]
With debug 10 it is expected to be slower as there is lots of debugging output.

**Comment by t-woerner** [comment]
You can speed up more by adding the upstream --noflush patch for ebtables-restore: http://git.netfilter.org/ebtables/commit/?id=3a25ae2361da048f24524d8e63d70f4cd40444f3

**Comment by SunilMohanAdapa** [comment]
On 06/27/2016 09:46 PM, Thomas Woerner wrote:
> With debug 10 it is expected to be slower as there is lots of debugging
> output.
> 

What is interesting is that with the same amount of output spewing, the
runProg() patch improves the performance drastically.

-- 
Sunil

**Comment by evgkrsk** [comment]
Upgrading 0.4.3 -> 0.4.3.1 breaks firewalld for me. I.e., "iptables -nvL"/"ip6tables -nvL" output is empty after upgrade. Additionally, "firewall-cmd --state" says "not running" and "firewallctl state" says "init" (while daemon is really up and running).

"systemctl stop firewalld" and running "/usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid --debug=10" produced following log:
```
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables will be using -w option.
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables will be using -w option.
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables-restore /run/firewalld/temp.6gUlMP: 0
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w -t filter -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w -t raw -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w -t security -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w -t mangle -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables -w -t nat -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w -t filter -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w -t raw -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w -t security -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w -t mangle -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipXtables.ip6tables'>: /sbin/ip6tables -w -t nat -L -n
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t filter -L
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t broute -L
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ebtables.ebtables'>: /sbin/ebtables --concurrent -t nat -L
2016-07-02 18:44:40 DEBUG1: start()
2016-07-02 18:44:40 DEBUG1: Loading firewalld config file '/etc/firewalld/firewalld.conf'
2016-07-02 18:44:40 DEBUG1: IPv6 rpfilter is enabled
2016-07-02 18:44:40 DEBUG1: LogDenied is set to 'off'
2016-07-02 18:44:40 DEBUG1: ebtables-restore is not supporting the --noflush option, will therefore not be used
2016-07-02 18:44:40 DEBUG2: <class 'firewall.core.ipset.ipset'>: /sbin/ipset list
2016-07-02 18:44:40 Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/firewall/server/decorators.py", line 51, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/server/firewalld.py", line 87, in start
    return self.fw.start()
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 368, in start
    self._start()
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 210, in _start
    self._start_check()
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 136, in _start_check
    self.ipset_backend.list()
  File "/usr/lib/python2.7/site-packages/firewall/core/ipset.py", line 162, in list
    return self.__run(args).split("\n")
  File "/usr/lib/python2.7/site-packages/firewall/core/ipset.py", line 82, in __run
    (status, ret) = runProg(self._command, _args)
  File "/usr/lib/python2.7/site-packages/firewall/core/prog.py", line 42, in runProg
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

2016-07-02 18:44:40 DEBUG1: GetAll('org.fedoraproject.FirewallD1')
2016-07-02 18:44:40 DEBUG1: config.GetAll('org.fedoraproject.FirewallD1.config')
```

```
$python --version
Python 2.7.11
```

**Comment by SunilMohanAdapa** [comment]
I was able to reproduce the problem by removing ipset package from my system and running firewalld.  I lead to this regression by not fully emulating the older runProg() behavior. My apologies.

I created a pull request #134 to fix the problem.

**Comment by t-woerner** [comment]
It has been merged, thanks.
