### ISSUE TITLE
continuing to fix reloads

### ISSUE THREAD

**Issue by kiorky** [t-woerner/firewalld#14]
Im on my way to get reload reworking as for now, i have another trace to inspect
```
2015-05-12 18:25:15 Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/firewall/server/decorators.py", line 57, in dbus_handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/firewall/server/firewalld.py", line 236, in reload
    self.fw.reload()
  File "/usr/lib/python2.7/dist-packages/firewall/core/fw.py", line 712, in reload
    self.direct.set_config(_direct_config)
  File "/usr/lib/python2.7/dist-packages/firewall/core/fw_direct.py", line 120, in set_config
    for (priority, args) in _rules[chain_id]:
TypeError: 'int' object is not iterable
```

**Comment by kiorky** [comment]
i think i have understood the problem, @t-woerner seems neither your patch nor mine which is in are good, :), in fact the key is (priority, args), but we need a dict, and the value is the priority.

**Comment by kiorky** [comment]
i have the patch, preparing pr.
