### ISSUE TITLE
ebtables-restore: Bad argument : 'COMMIT'

### ISSUE THREAD

**Issue by rossmcdonald** [t-woerner/firewalld#158]
On a fresh install of Fedora 24 (`firewalld-0.4.1.2-1.fc24.noarch`/`ebtables-2.0.10-20.fc24.x86_64`), I'm seeing this error when starting firewalld:

```
2016-10-17 22:18:01 Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/firewall/server/decorators.py", line 51, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/firewall/server/firewalld.py", line 85, in start
    return self.fw.start()
  File "/usr/lib/python3.5/site-packages/firewall/core/fw.py", line 325, in start
    self._start()
  File "/usr/lib/python3.5/site-packages/firewall/core/fw.py", line 304, in _start
    self._apply_default_rules()
  File "/usr/lib/python3.5/site-packages/firewall/core/fw.py", line 645, in _apply_default_rules
    self.__apply_default_rules(ipv)
  File "/usr/lib/python3.5/site-packages/firewall/core/fw.py", line 641, in __apply_default_rules
    self.rules(ipv, rules[ipv])
  File "/usr/lib/python3.5/site-packages/firewall/core/fw.py", line 850, in rules
    return self.ebtables_backend.set_rules(_rules)
  File "/usr/lib/python3.5/site-packages/firewall/core/ebtables.py", line 161, in set_rules
    " ".join(args), ret))
ValueError: '/usr/sbin/ebtables-restore --noflush' failed: Bad argument : 'COMMIT'.
```

Triggered [here](https://github.com/t-woerner/firewalld/blob/master/src/firewall/core/ebtables.py#L174). The error seems to leave the firewall in an inconsistent state, as it prevents new connections to the instance. After some troubleshooting, I was able to collect the following file, which is what is piped to `ebtables-restore`:

```
*broute
-F
-X
-Z
COMMIT

*filter
-F
-X
-Z
COMMIT

*nat
-F
-X
-Z
COMMIT

*broute
-N BROUTING_direct -P RETURN
-I BROUTING 1 -j BROUTING_direct
COMMIT

*filter
-N INPUT_direct -P RETURN
-I INPUT 1 -j INPUT_direct
-N OUTPUT_direct -P RETURN
-I OUTPUT 1 -j OUTPUT_direct
-N FORWARD_direct -P RETURN
-I FORWARD 1 -j FORWARD_direct
COMMIT

*nat
-N PREROUTING_direct -P RETURN
-I PREROUTING 1 -j PREROUTING_direct
-N POSTROUTING_direct -P RETURN
-I POSTROUTING 1 -j POSTROUTING_direct
-N OUTPUT_direct -P RETURN
-I OUTPUT 1 -j OUTPUT_direct
COMMIT
```

Unfortunately I know next to nothing about `ebtables`, or why the syntax above is incorrect. Googling hasn't turned up very much, but let me know if there's any information I can provide to help find the issue (or if there's something misconfigured with my instance).

**Comment by t-woerner** [comment]
Please update to a newer firewalld version available in the fedora 24 updates. This issue has been fixed already.

**Comment by rossmcdonald** [comment]
Updated and the issue is indeed fixed. Thanks!
