### ISSUE TITLE
Setting description/short on ipsets fails.

### ISSUE THREAD

**Issue by crayfishx** [t-woerner/firewalld#214]
I've seen https://github.com/t-woerner/firewalld/issues/161 but that appears to be related just to zones....  Currently I'm trying to get this working with ipsets...

Currently testing this with `firewalld-0.4.3.2-8.1.el7_3.2.noarch`

```
[root@localhost lib]# firewall-cmd --permanent --new-ipset=tango --type=hash:ip
success
```

```
[root@localhost lib]# firewall-cmd --permanent --ipset=tango --set-description="a test ipset"
Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 53, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 441, in update
    self.fw_zone.update(tuple(settings.settings))
AttributeError: 'FirewallClientConfigZone' object has no attribute 'settings'
```

```
[root@localhost lib]# firewall-cmd --permanent --ipset=tango --set-short="a test ipset"
Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 53, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 441, in update
    self.fw_zone.update(tuple(settings.settings))
AttributeError: 'FirewallClientConfigZone' object has no attribute 'settings'
```

**Comment by t-woerner** [comment]
This has already been fixed with https://github.com/t-woerner/firewalld/commit/e2ada7761d6287e90e8404379fae03dcbd3e9a5e

Please have a look at  https://bugzilla.redhat.com/show_bug.cgi?id=1416325
