### ISSUE TITLE
Cannot change zone of an interface from firewall-config

### ISSUE THREAD

**Issue by bigon** [t-woerner/firewalld#26]
Hi,

With 0.3.14.2, I get the following error when trying to change the zone of an interface from firewall-config:

```python
Traceback (most recent call last):
  File "/usr/bin/firewall-config", line 1014, in change_zone_connection_editor
    editor.run()
  File "/usr/bin/firewall-config", line 5318, in run
    connection_obj.Update(settings)
  File "/usr/lib/python2.7/dist-packages/slip/dbus/proxies.py", line 51, in __call__
    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 7 matched rules; type="method_call", sender=":1.623" (uid=1000 pid=16498 comm="/usr/bin/python -Es /usr/bin/firewall-config ") interface="(unset)" member="Update" error name="(unset)" requested_reply="0" destination=":1.12" (uid=0 pid=1125 comm="/usr/sbin/NetworkManager --no-daemon ")
```

With 0.3.13 the backtrace was a bit different

**Comment by t-woerner** [comment]
What was the error message with the old version?

**Comment by bigon** [comment]
Same as reported at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=767888

```python
On the console, I get
Traceback (most recent call last):
  File "/usr/bin/firewall-config", line 1007, in change_zone_connection_editor
    editor.run()
  File "/usr/bin/firewall-config", line 5298, in run
    settings = connection_obj.GetSettings()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/slip/dbus/proxies.py", line 51, in __call__
    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 7 matched rules; type="method_call", sender=":1.63" (uid=1000 pid=28011 comm="/usr/bin/python -Es /usr/bin/firewall-config ") interface="(unset)" member="GetSettings" error name="(unset)" requested_reply="0" destination=":1.14" (uid=0 pid=1039 comm="/usr/sbin/NetworkManager --no-daemon ")
```

**Comment by t-woerner** [comment]
Are you allowed as this user to modify the connectino in NetworkManager? Is the interface used by several connections, where you are not allowed to change one of them?

**Comment by bigon** [comment]
Yes I can perfectly change it using gnome-control-center.

I think I should be able to change everything for any connection

**Comment by t-woerner** [comment]
I am not able to reproduce this. Is this a wireless or wired connection? Is the interface used also for other connections in NetworkManager?

**Comment by bigon** [comment]
I can reproduce this with my desktop as well.

Here it's a wired network and the interface is only used for one connection.

I forgot to mention that I was on debian unstable

**Comment by t-woerner** [comment]
Is this also an issue with firewall-applet or only with firewall-config?
Do you maybe have a debian unstable qemu image that is affected by this issue?

**Comment by bigon** [comment]
Yes I get the same issue with firewall-applet:

```python
Traceback (most recent call last):
  File "/usr/bin/firewall-applet", line 763, in change_zone_connection_editor
    editor.run()
  File "/usr/bin/firewall-applet", line 174, in run
    settings = connection_obj.GetSettings()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/slip/dbus/proxies.py", line 51, in __call__
    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 8 matched rules; type="method_call", sender=":1.207" (uid=1000 pid=16380 comm="/usr/bin/python -Es /usr/bin/firewall-applet ") interface="(unset)" member="GetSettings" error name="(unset)" requested_reply="0" destination=":1.14" (uid=0 pid=1492 comm="/usr/sbin/NetworkManager --no-daemon ")
^CTraceback (most recent call last):
  File "/usr/bin/firewall-applet", line 1188, in <module>
    mainloop.run()
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 575, in run
    raise KeyboardInterrupt
KeyboardInterrupt
```

**Comment by bigon** [comment]
You can dowload a debian VM with the issue at https://people.debian.org/~bigon/debian8_firewalld.qcow2
